version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    # Check for updates once a week
    schedule:
      interval: "daily"
      time: "11:00"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
      time: "11:00"
