build:
  environment:
    python: 3.7.9
  dependencies:
    override:
      - "pip install -r requirements.txt -r requirements-test.txt"
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run

checks:
  python:
    duplicate_code: false
